/*
 * TravelPins data file
 * ---------------------
 * A personal Sydney coffee map imported from field notes.
 *
 * Rating (1-5 stars) is mapped from the source score out of 10.
 * Address, tasting notes, price and score live in `notes`.
 * Coordinates are street-level geocodes from each row's address.
 * Drag any pin in the app to fine-tune.
 *
 * Fields: name, city, area, category, lat, lng, rating, notes, image/images (optional)
 * Decision fields: recommended, score, traits, whyGo, skipIf
 * Memory fields: visitedAt, addedAt (ISO dates, optional)
 */
window.TRAVEL_PINS_VERSION = "roaming-scroll-2026-07-24.1";
window.TRAVEL_PINS = [
  { name: "Central Roasters Coffee", city: "Sydney", area: "CBD", category: "coffee", lat: -33.875627, lng: 151.207507, rating: 4, recommended: true, score: 7, traits: ["Recommended", "Creamy milk", "Sit down", "Cheap"], whyGo: "A dependable CBD pick with creamy milk, balanced coffee, seating, and cheap breakfast deals.", skipIf: "Skip if you want the strongest cup on the list.", notes: "8/10 Central St, Sydney NSW 2000. Nice balance between coffee taste and milk; milk is good quality and quite creamy. Cozy sitting area, has cheap breakkie deals. Score 7/10 - recommended. $4.00 / $4.50." },
  { name: "Ok Cool", city: "Sydney", area: "CBD", category: "coffee", lat: -33.874336, lng: 151.206551, rating: 1, recommended: false, score: 2, traits: ["Skip", "Cheap"], whyGo: "Keep this one for when price matters more than the coffee.", skipIf: "You want a cup with body or flavour.", notes: "119 Bathurst St, Sydney NSW 2000. Weak and tasteless; milk is below average. Small space, inexperienced barista. Score 2/10 - not recommended. $4.00 / $4.50." },
  { name: "Cup & Co coffee bar", city: "Sydney", area: "CBD", category: "coffee", lat: -33.876800, lng: 151.208600, rating: 3, recommended: false, score: 6.5, traits: ["Breakfast deal", "Strong body"], whyGo: "A fuller-bodied coffee with a handy breakfast deal.", skipIf: "You prefer creamy milk or very little bitterness.", notes: "265 Castlereagh St, Sydney NSW 2000. Medium to full coffee body, somewhat bitter; milk is average and not quite creamy. Good breakie deal, free shortbread with coffee. Score 6.5/10 - not recommended. $4.20 / $5.00." },
  { name: "Jim & Co", city: "Sydney", area: "CBD", category: "coffee", lat: -33.875998, lng: 151.208349, rating: 4, recommended: true, score: 7.5, traits: ["Recommended", "Strong body", "Creamy milk", "Easy stop"], whyGo: "Strong coffee without too much bitterness, with creamy milk and an easy CBD location.", skipIf: "You want somewhere spacious enough to linger.", notes: "233 Castlereagh St, Sydney NSW 2000. Strong coffee body without too much bitterness; good, creamy milk. Good price and taste, close to the office. Score 7.5/10 - recommended. $4.50 / $5.00." },
  { name: "Shortcut Cafe", city: "Sydney", area: "Haymarket", category: "coffee", lat: -33.879284, lng: 151.206584, rating: 4, recommended: true, score: 7, traits: ["Recommended", "Strong body", "Creamy milk", "Hidden spot"], whyGo: "A hidden Haymarket option with strong coffee and very nice creamy milk.", skipIf: "Skip if consistency under pressure matters today.", notes: "Unit 701/4-10 Campbell St, Haymarket NSW 2000. Strong and decent coffee taste; creamy, very nice milk. Hidden down a small street; barista is less consistent under pressure. Score 7/10 - recommended. $4.80 / $5.50." },
  { name: "Kingswood Coffee", city: "Sydney", area: "CBD", category: "coffee", lat: -33.875391, lng: 151.207941, rating: 5, recommended: true, score: 9.5, traits: ["Top pick", "Recommended", "Creamy milk", "Consistent"], whyGo: "One of the favourites: consistently good coffee with creamy milk.", skipIf: "You dislike thinner or fruitier coffee.", notes: "395 Pitt St, Sydney NSW 2000. Thin to medium body with a fruity note; good quality and quite creamy milk. Great consistency; piccolo costs the same as a regular. Score 9.5/10 - recommended, top pick. $5.00 / $5.80." },
  { name: "Single O", city: "Sydney", area: "Surry Hills", category: "coffee", lat: -33.881180, lng: 151.209681, rating: 3, recommended: false, score: 6, traits: ["Long walk", "Fruity", "Skip"], whyGo: "A familiar Surry Hills name when you feel like something lighter and fruitier.", skipIf: "You want strong coffee, good value or a nearby stop.", notes: "60/64 Reservoir St, Surry Hills NSW 2010. Typical Surry Hills coffee, thin body; milk is average and a bit watery. Long walk from office, pricey; not suitable if you like strong coffee. Score 6/10 - not recommended. $5.50 / $6.00." },
  { name: "Joe Black Cafe", city: "Sydney", area: "CBD", category: "coffee", lat: -33.877614, lng: 151.211063, rating: 4, recommended: true, score: 7.5, traits: ["Recommended", "Full body", "Sit down", "Natural sweetness"], whyGo: "Full-bodied coffee, naturally sweet milk and enough seating to stay for a while.", skipIf: "You need a very quick takeaway.", notes: "27 Commonwealth St, Sydney NSW 2000. Full-bodied coffee with great balance; milky with natural sweetness. Indoor and outdoor seating; great to sit down with food. Score 7.5/10 - recommended. $4.00 / $5.00." },
  { name: "Bearded Bear Cafe", city: "Sydney", area: "CBD", category: "coffee", lat: -33.880047, lng: 151.205235, rating: 4, recommended: true, score: 8.5, traits: ["Top pick", "Recommended", "Cheap", "Consistent"], whyGo: "Little Marionette beans, a good price and a barista who stays consistent when it gets busy.", skipIf: "You want especially creamy milk today.", notes: "570 George St, Sydney NSW 2000. Little Marionette beans, balanced and just right. Milk is alright; a little creamier would be perfect. Great barista under pressure and good price. Score 8.5/10 - recommended. $4.00 / $4.80." },
  { name: "Hydeaway", city: "Sydney", area: "CBD", category: "coffee", lat: -33.880595, lng: 151.208847, rating: 4, recommended: true, score: 7, traits: ["Recommended", "Creamy milk", "Balanced", "Fruity"], whyGo: "A balanced, creamy cup when you feel like something lighter and smoother.", skipIf: "You want a strong coffee hit.", notes: "120 Elizabeth St, Hydeaway Cafe, Sydney NSW 2000. Thin to medium body with a fruity note; creamy and balanced. Nice overall, but not for strong-coffee lovers. Score 7/10 - recommended. $4.50 / $5.50." },
  { name: "Le MONDE Bakery-Cafe", city: "Sydney", area: "CBD", category: "coffee", lat: -33.874634, lng: 151.209389, rating: 4, recommended: true, score: 8, traits: ["Recommended", "Cheap", "Balanced", "Breakfast deal"], whyGo: "Affordable Campos coffee with good balance, natural sweetness and a handy breakfast combo.", skipIf: "You’re looking for a specialty-coffee destination.", notes: "100 Bathurst St, Sydney NSW 2000. Campos beans with balanced, medium-body coffee. Great milk temperature and natural sweetness. Cheap and tasty coffees, decent breakkie combo. Score 8/10 - recommended. $3.90 / $4.50." },
  { name: "Hendry's Coffee", city: "Sydney", area: "Darlinghurst", category: "coffee", lat: -33.878267, lng: 151.221262, rating: 5, recommended: true, score: 9, traits: ["Top pick", "Recommended", "Strong body", "Creamy milk"], whyGo: "Strong coffee, creamy milk and Melbourne beans make this worth the walk.", skipIf: "Darlinghurst feels too far today.", notes: "144-150 Liverpool St, Darlinghurst NSW 2010. Pretty strong, medium to full body coffee; good, creamy milk. Melbourne beans with strong flavour, very good. Score 9/10 - recommended. $4.80 / $5.50." },
  { name: "The Walrus Sydney CBD", city: "Sydney", area: "CBD", category: "coffee", lat: -33.874019, lng: 151.208351, rating: 4, recommended: true, score: 7, traits: ["Recommended", "Creamy milk", "Cheap"], whyGo: "A reliable, good-value cup with creamy milk.", skipIf: "You want one of the more distinctive favourites.", notes: "Shop 1/276 Pitt St, Sydney NSW 2000. Average but nice coffee; good, creamy milk. Good coffee for the price. Score 7/10 - recommended. $4.00 / $4.70." },
  { name: "Rang Cafe", city: "Sydney", area: "CBD", category: "coffee", lat: -33.875878, lng: 151.208469, rating: 5, recommended: true, score: 9, traits: ["Top pick", "Recommended", "Creamy milk", "ONA beans"], whyGo: "Balanced ONA coffee, creamy milk and excellent value.", skipIf: "You feel like exploring beyond the usual CBD streets.", notes: "Lobby/233 Castlereagh St, Sydney NSW 2000. Balanced and just right; good, creamy milk. Decent coffee at a great price, using ONA beans. Score 9/10 - recommended. $4.50 / $5.00." },
  { name: "Coffee Pitt", city: "Sydney", area: "CBD", category: "coffee", lat: -33.875907, lng: 151.207712, rating: 4, recommended: true, score: 7, traits: ["Recommended", "Strong body", "Bitter"], whyGo: "Choose this when you want a strong, bitter coffee.", skipIf: "You’re after something balanced or creamy.", notes: "367 Pitt St, Sydney NSW 2000. Leaning toward the strong and bitter side. Go for it if you want a strong, bitter coffee. Score 7/10 - recommended. $4.30 / $5.00." },
  { name: "Ek'sentrik Cafe (Side of Belvedere Hotel on Bathust street)", city: "Sydney", area: "CBD", category: "coffee", lat: -33.874583, lng: 151.205553, rating: 4, recommended: true, score: 8.5, traits: ["Top pick", "Recommended", "Cheap", "Creamy milk"], whyGo: "Balanced, creamy Campos coffee at one of the best prices on the map.", skipIf: "You need somewhere obvious and easy to spot.", notes: "484 Kent St, Sydney NSW 2000. Balanced and creamy. Campos beans at this price: you cannot go wrong. Score 8.5/10 - recommended. $3.70 / $4.20." },
  { name: "Stitch Coffee QVB", city: "Sydney", area: "CBD", category: "coffee", lat: -33.871435, lng: 151.206669, rating: 4, recommended: true, score: 8, traits: ["Recommended", "Balanced", "Pastries", "Pricey"], whyGo: "Balanced coffee, great pastries, tap coffees, and experienced baristas.", skipIf: "Skip if price is the deciding factor today.", notes: "Ground Level QVB, Shop G054/455 George St, Sydney NSW 2000. Balanced, not weak or overly fruity. Great pastries, tap coffees and experienced baristas; price is the only drawback. Score 8/10 - recommended. $6.00 / $6.50." },
  { name: "Dutch Smuggler Coffee QVB", city: "Sydney", area: "CBD", category: "coffee", lat: -33.871315, lng: 151.206789, rating: 3, recommended: false, score: 5.5, traits: ["Skip", "Pricey"], whyGo: "Keep it in mind only when you’re already inside the QVB.", skipIf: "Value matters; the coffee felt below average for the price.", notes: "Queen Victoria Building, lower ground level 2 Shop 11/455 George St, Sydney NSW 2000. Slightly below average and not good for the price. Score 5.5/10 - not recommended. $6.00." },
  { name: "Leible Coffee", city: "Sydney", area: "CBD", category: "coffee", lat: -33.869870, lng: 151.205996, rating: 5, recommended: true, score: 9, traits: ["Top pick", "Recommended", "Balanced", "Medium roast"], whyGo: "A beautifully balanced medium roast, up there with the favourites.", skipIf: "You want a darker or stronger coffee.", notes: "Ground Floor Cafe, 89 York St, Sydney NSW 2000. Very nice and balanced; everything blends well together. Kingswood-level quality, medium-roast bean profile. Score 9/10 - recommended. $5.50." },
  { name: "Skittle Lane", city: "Sydney", area: "CBD", category: "coffee", lat: -33.868989, lng: 151.209002, rating: 4, recommended: true, score: 8, traits: ["Recommended", "Smooth", "Balanced"], whyGo: "Smooth, well-balanced coffee in a handy King Street spot.", skipIf: "You’re keeping the coffee budget low today.", notes: "40 King St, Sydney NSW 2000. Real smooth and well balanced. Score 8/10 - recommended. $5.50 / $6.50." },

  { name: "Chinatown Country Club - Coffee House", city: "Sydney", area: "CBD", category: "coffee", lat: -33.870762, lng: 151.205222, rating: 0, recommended: true, score: 0, traits: ["Visited together", "Memory", "Good vibe", "Roomy", "Mixed coffee notes"], whyGo: "A warm Clarence Street memory with good vibe and room for the group to pause together.", skipIf: "Coffee value matters more than the room and mood today.", notes: "222 Clarence St, Sydney NSW 2000. Team coffee tour on 24 July 2026. Recommended by a friend; the room and vibe landed well. Coffee feedback was mixed across the group, and the usual small-size price gap came up again.", image: "assets/chinatown-country-club-team-2026-07-24-1.jpg", images: ["assets/chinatown-country-club-team-2026-07-24-1.jpg", "assets/chinatown-country-club-team-2026-07-24-2.jpg"], visitedAt: "2026-07-24", updateKey: "chinatown-country-club-team-tour-2026-07-24" },

  { name: "Seven Miles Cafe", city: "Sydney", area: "CBD", category: "coffee", lat: -33.871819, lng: 151.207601, rating: 4, recommended: true, score: 7.5, traits: ["Recommended", "Sit down", "Roomy", "Team visit"], whyGo: "A comfortable CBD pause with a solid cup and plenty of room for the whole group.", skipIf: "You want one of the map’s more distinctive coffee destinations.", notes: "488 George St, Sydney NSW 2000, inside Hilton Sydney. Overall good coffee with nothing to complain about; plenty of tables and chairs. Score 7.5/10 - recommended. $5.50 / $6.00. Team coffee tour on 17 July 2026.", image: "assets/seven-miles-team-2026-07-17-1.jpg", images: ["assets/seven-miles-team-2026-07-17-1.jpg", "assets/seven-miles-team-2026-07-17-2.jpg"], visitedAt: "2026-07-17", updateKey: "seven-miles-team-tour-2026-07-17" },

  // Kept from an earlier shared visit.
  { name: "Meisterstück", city: "Sydney", area: "CBD", category: "coffee", lat: -33.869244, lng: 151.204983, rating: 0, recommended: true, score: 0, traits: ["Visited together", "Memory"], whyGo: "A recent coffee-tour memory, saved so it’s easy to find again.", skipIf: "You only want somewhere you haven’t visited yet.", notes: "185 Clarence St, Sydney NSW 2000. Team coffee tour on 10 July 2026.", image: "assets/meisterstuck-team-2026-07-10.jpg", visitedAt: "2026-07-10", updateKey: "meisterstuck-team-tour-2026-07-10" }
];
